#!/usr/bin/env python3
"""
tars-lora validation gate — runs the ML model through the formal
walk-forward/PBO/Calmar validation pipeline (src/validation.py).

Loads data/carry/dataset.csv (generated by build_carry_dataset.py),
maps features to the model's expected prompt format, gets predictions,
simulates carry trade returns, and evaluates against the validation gate.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

# In Colab notebooks, __file__ is not defined — fall back to cwd
try:
    REPO = Path(__file__).resolve().parent.parent
except NameError:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))

from src.validation import (
    walk_forward_windows,
    validation_report,
    probability_of_backtest_overfitting,
    sharpe_ratio,
    calmar_ratio,
    max_drawdown,
    cagr,
    PERIODS_PER_YEAR,
)

# Model expects these 6 features in prompt:
# "Funding {rate} basis {bps} vol {vol} ret {ret} 7d_mean {mean} z {z} -> will 7d carry clear costs?"
# Maps from dataset.csv columns:
# f0 -> funding_rate
# basis_bps -> basis
# vol_24h -> vol
# ret_24h -> ret
# f_mean7d -> 7d_mean
# f_z30d -> z

FEATURE_MAP = {
    "funding_rate": "f0",
    "basis_bps": "basis_bps",
    "vol": "vol_24h",
    "ret": "ret_24h",
    "funding_7d_mean": "f_mean7d",
    "funding_z_score": "f_z30d",
}

# Label columns
LABEL_Y7D = "y_sum_7d_bps"
LABEL_YWIN = "y_win"
LABEL_YFLIP = "y_flip"

COST_BPS = 35.0  # round-trip cost assumption (both legs)
EV_MARGIN = 2.0  # need 2x costs to count as "win"

# Fold-level resume checkpoints (local only, gitignored). The model is
# deterministic (do_sample=False), so resumed folds are bit-identical to
# an uninterrupted run. A dataset fingerprint in manifest.json guards
# against reusing stale checkpoints after the dataset changes.
CHECKPOINT_DIR_NAME = "tars_lora_checkpoints"
TRAIN_CHUNK_ROWS = 2000  # save train-prediction progress every N rows


def _dataset_fingerprint(df: pd.DataFrame, n_folds: int, train_frac: float) -> dict:
    """Fingerprint the dataset + split config. Any change invalidates checkpoints."""
    return {
        "rows": int(len(df)),
        "ts_min": int(df["ts"].min()),
        "ts_max": int(df["ts"].max()),
        "n_folds": n_folds,
        "train_frac": train_frac,
    }


def _init_checkpoint_dir(checkpoint_dir: Path, fingerprint: dict, fresh: bool) -> dict:
    """Validate manifest against the current dataset. Returns manifest dict.

    If `fresh` or the fingerprint mismatches (or manifest is missing/corrupt),
    wipes the dir and writes a new manifest. Otherwise keeps existing folds.
    """
    import json

    manifest_path = checkpoint_dir / "manifest.json"
    if fresh and checkpoint_dir.exists():
        print("  --fresh: discarding all checkpoints")
        for p in checkpoint_dir.glob("*"):
            p.unlink()
    if checkpoint_dir.exists() and manifest_path.exists():
        try:
            saved = json.loads(manifest_path.read_text())
            if saved.get("fingerprint") == fingerprint:
                done = sorted(p.name for p in checkpoint_dir.glob("fold_*.npz"))
                print(f"  Resuming: {len(done)} completed folds found ({', '.join(done) or 'none'})")
                return saved
            print("  Dataset/split changed since last run: discarding stale checkpoints")
            for p in checkpoint_dir.glob("*"):
                p.unlink()
        except (json.JSONDecodeError, OSError) as e:
            print(f"  Corrupt manifest ({e}): starting fresh")
            for p in checkpoint_dir.glob("*"):
                p.unlink()
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    manifest = {"fingerprint": fingerprint}
    manifest_path.write_text(json.dumps(manifest, indent=2))
    return manifest


def _metrics_from_arrays(returns: np.ndarray, predictions: np.ndarray) -> dict:
    """Recompute fold metrics from saved arrays (identical formulas to evaluate_model_on_fold)."""
    return {
        "sharpe": sharpe_ratio(returns),
        "calmar": calmar_ratio(returns),
        "max_drawdown": max_drawdown(returns),
        "cagr": cagr(returns),
        "num_trades": int(np.sum(predictions)),
        "win_rate": float(np.mean(predictions)) if len(predictions) > 0 else 0.0,
        "returns": returns,
        "predictions": predictions,
    }


def load_dataset() -> pd.DataFrame:
    """Load the carry dataset."""
    path = REPO / "data" / "carry" / "dataset.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"Dataset not found at {path}. Run scripts/fetch_carry_data.py "
            f"and scripts/build_carry_dataset.py first (requires Binance API access)."
        )
    df = pd.read_csv(path)
    return df


def simulate_carry_returns(
    df: pd.DataFrame,
    predictions: np.ndarray,  # 1 = YES (enter carry), 0 = NO (flat)
) -> np.ndarray:
    """
    Simulate returns from model decisions.

    When model predicts YES (1): enter long-spot/short-perp carry trade.
    Return = next 7d cumulative funding (y_sum_7d_bps) minus round-trip costs.
    When model predicts NO (0): stay flat, return = 0.

    Returns per-period (8h) returns for Sharpe/Calmar calculation.
    """
    # The dataset is at funding settlement cadence (every 8h normalized)
    # y_sum_7d_bps is cumulative funding over next 7 days (21 periods)
    # We need to convert to per-period returns

    y7d = df[LABEL_Y7D].values / 10000.0  # convert bps to decimal
    ywin = df[LABEL_YWIN].values

    # When model says YES, we collect the 7d funding spread over 21 periods
    # Per-period return = y7d / 21 - cost_per_period
    # Cost is round-trip (enter + exit) = 35 bps = 0.0035
    # Amortized over 21 periods = 0.0035 / 21 per period

    cost_per_period = COST_BPS / 10000.0 / 21

    returns = np.zeros(len(df))
    for i in range(len(df)):
        if predictions[i] == 1:
            # Model says enter carry trade
            if not np.isnan(y7d[i]):
                returns[i] = y7d[i] / 21.0 - cost_per_period
            else:
                returns[i] = -cost_per_period  # just cost if no forward data
        else:
            returns[i] = 0.0

    return returns


def evaluate_model_on_fold(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    model_predict_func,
) -> dict:
    """Evaluate model on a single walk-forward fold."""
    # Get test predictions
    test_predictions = []
    for _, row in test_df.iterrows():
        features = {}
        for model_feat, df_col in FEATURE_MAP.items():
            val = row.get(df_col, np.nan)
            features[model_feat] = float(val) if not np.isnan(val) else 0.0

        # Call model predict function
        pred = model_predict_func(features)
        test_predictions.append(1 if pred else 0)

    test_predictions = np.array(test_predictions)

    # Simulate returns
    returns = simulate_carry_returns(test_df, test_predictions)

    # Compute metrics
    metrics = {
        "sharpe": sharpe_ratio(returns),
        "calmar": calmar_ratio(returns),
        "max_drawdown": max_drawdown(returns),
        "cagr": cagr(returns),
        "num_trades": int(np.sum(test_predictions)),
        "win_rate": float(np.mean(test_predictions)) if len(test_predictions) > 0 else 0.0,
        "returns": returns,
        "predictions": test_predictions,
    }

    return metrics


def run_walk_forward_validation(
    df: pd.DataFrame,
    model_predict_func,
    n_folds: int = 6,
    train_frac: float = 0.7,
    checkpoint_dir: Path | None = None,
    fresh: bool = False,
) -> dict:
    """Run full walk-forward validation with purged splits.

    When `checkpoint_dir` is given, each completed fold's returns/predictions
    are saved to `fold_{idx}.npz` and skipped on re-run (resume). A manifest
    fingerprint guards against stale checkpoints after dataset changes.
    """
    # Dataset already has fold/split columns from build script
    # But we re-compute to ensure consistency with validation.py logic

    # Sort by timestamp
    df = df.sort_values("ts").reset_index(drop=True)

    # Get unique timestamps for walk-forward
    unique_ts = df["ts"].unique()
    unique_ts.sort()

    if checkpoint_dir is not None:
        _init_checkpoint_dir(
            checkpoint_dir, _dataset_fingerprint(df, n_folds, train_frac), fresh
        )

    all_test_returns = []
    all_test_predictions = []
    fold_results = []

    for fold_idx, (train_slice, test_slice) in enumerate(
        walk_forward_windows(len(unique_ts), n_folds, train_frac)
    ):
        train_ts = unique_ts[train_slice]
        test_ts = unique_ts[test_slice]

        train_mask = df["ts"].isin(train_ts)
        test_mask = df["ts"].isin(test_ts)

        # Apply embargo: drop train rows whose label could straddle test window
        # Embargo = 7 days = 7 * 24 * 3600 * 1000 ms
        EMBARGO_MS = 7 * 24 * 3600 * 1000
        train_max_ts = train_ts.max()
        embargo_mask = ~((df["ts"] > train_max_ts - EMBARGO_MS) & train_mask)
        train_mask = train_mask & embargo_mask

        train_df = df[train_mask].copy()
        test_df = df[test_mask].copy()

        print(f"\nFold {fold_idx}: train={len(train_df)}, test={len(test_df)}")

        if len(test_df) == 0:
            print("  Skipping: no test data")
            continue

        # Resume: recompute metrics from saved arrays, skip inference
        ckpt_path = checkpoint_dir / f"fold_{fold_idx}.npz" if checkpoint_dir else None
        if ckpt_path is not None and ckpt_path.exists():
            saved = np.load(ckpt_path)
            fold_result = _metrics_from_arrays(
                saved["returns"], saved["predictions"]
            )
            print(f"  Resumed from checkpoint (no inference)")
        else:
            # Evaluate on this fold
            fold_result = evaluate_model_on_fold(train_df, test_df, model_predict_func)
            if ckpt_path is not None:
                np.savez_compressed(
                    ckpt_path,
                    returns=fold_result["returns"],
                    predictions=fold_result["predictions"],
                )
                print(f"  Checkpoint saved: {ckpt_path.name}")
        fold_results.append(fold_result)

        all_test_returns.extend(fold_result["returns"])
        all_test_predictions.extend(fold_result["predictions"])

        print(f"  Sharpe: {fold_result['sharpe']:.3f}, Calmar: {fold_result['calmar']:.3f}")
        print(f"  Trades: {fold_result['num_trades']}, Win rate: {fold_result['win_rate']:.1%}")

    all_test_returns = np.array(all_test_returns)
    all_test_predictions = np.array(all_test_predictions)

    # Overall metrics
    overall = {
        "sharpe": sharpe_ratio(all_test_returns),
        "calmar": calmar_ratio(all_test_returns),
        "max_drawdown": max_drawdown(all_test_returns),
        "cagr": cagr(all_test_returns),
        "num_trades": int(np.sum(all_test_predictions)),
        "win_rate": float(np.mean(all_test_predictions)) if len(all_test_predictions) > 0 else 0.0,
        "fold_results": fold_results,
    }

    return overall


def run_pbo_analysis(
    df: pd.DataFrame,
    model_predict_func,
    param_grid: list[dict] | None = None,
) -> dict:
    """
    Run Probability of Backtest Overfitting analysis.

    For tars-lora, we don't have a parameter grid (fixed model).
    But we can simulate by running with different confidence thresholds
    or by comparing against baseline strategies.
    """
    if param_grid is None:
        # No parameter sweep for a fixed model
        return {"pbo": 0.0, "pbo_pass": True, "n_combinations_tested": 1, "warning": None}

    # If param_grid provided, evaluate each variant
    is_sharpes = []
    oos_sharpes = []

    for params in param_grid:
        # Would need to retrain or adjust model per params
        # Not applicable for fixed tars-lora
        pass

    return {"pbo": 0.0, "pbo_pass": True, "n_combinations_tested": 1, "warning": None}


def predict_train_chunked(
    train_df: pd.DataFrame,
    model_predict_func,
    checkpoint_dir: Path,
    fingerprint: dict,
    chunk_rows: int = TRAIN_CHUNK_ROWS,
) -> np.ndarray:
    """Predict over all train rows, saving progress every `chunk_rows`.

    Resume-safe: `train_progress.json` records completed rows + dataset
    fingerprint. A fingerprint mismatch discards partial progress.
    """
    import json

    progress_path = checkpoint_dir / "train_progress.json"
    preds_path = checkpoint_dir / "train_predictions.npy"
    done = 0
    if progress_path.exists() and preds_path.exists():
        try:
            progress = json.loads(progress_path.read_text())
            if progress.get("fingerprint") == fingerprint:
                done = int(progress.get("done", 0))
                print(f"  Resuming train predictions from row {done}/{len(train_df)}")
            else:
                print("  Train fingerprint changed: restarting train predictions")
        except (json.JSONDecodeError, OSError) as e:
            print(f"  Corrupt train progress ({e}): restarting train predictions")

    predictions = (
        list(np.load(preds_path)) if done > 0 and preds_path.exists() else []
    )
    # Guard against a longer saved array than the current frame (dataset shrank)
    predictions = predictions[:done]

    rows = list(train_df.iterrows())
    for i in range(done, len(rows)):
        _, row = rows[i]
        features = {}
        for model_feat, df_col in FEATURE_MAP.items():
            val = row.get(df_col, np.nan)
            features[model_feat] = float(val) if not np.isnan(val) else 0.0
        predictions.append(1 if model_predict_func(features) else 0)
        if (i + 1) % chunk_rows == 0 or (i + 1) == len(rows):
            np.save(preds_path, np.array(predictions, dtype=np.int8))
            progress_path.write_text(json.dumps(
                {"done": i + 1, "fingerprint": fingerprint}
            ))
            print(f"  Train predictions: {i + 1}/{len(rows)}", flush=True)

    return np.array(predictions, dtype=np.int8)


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--fresh", action="store_true",
                    help="discard all checkpoints and start over")
    args = ap.parse_args()

    print("=" * 80)
    print("TARS-LORA VALIDATION GATE")
    print("=" * 80)
    print(f"REPO = {REPO}")
    if args.fresh:
        print("Mode: FRESH (checkpoints discarded)")

    # Check if model exists
    adapter_path = REPO / "tars-lora-repo" / "lora_model"
    if not adapter_path.exists():
        print(f"Model adapter not found at {adapter_path}")
        print("Expected: tars-lora-repo/lora_model/adapter_model.safetensors")
        return 1

    # Load dataset
    print("Loading dataset...")
    try:
        df = load_dataset()
        print(f"Loaded {len(df)} rows")
        print(f"Columns: {len(df.columns)}")
        print(f"Test rows: {(df['split'] == 'test').sum()}")
        print(f"Train rows (usable): {((df['split'] == 'train') & df['usable']).sum()}")
    except FileNotFoundError as e:
        print(e)
        return 1

    # Import and initialize model
    print("\nInitializing tars-lora model...")
    try:
        from src.ml_inference import CarryFeatures, get_tars_lora_client
        client = get_tars_lora_client()
        client.load()
        print("Model loaded successfully")
    except Exception as e:
        print(f"Failed to load model: {e}")
        return 1

    def model_predict(features: dict) -> bool:
        """Predict whether 7d carry will clear costs."""
        cf = CarryFeatures(
            funding_rate=features["funding_rate"],
            basis_bps=features["basis_bps"],
            vol=features["vol"],
            ret=features["ret"],
            funding_7d_mean=features["funding_7d_mean"],
            funding_z_score=features["funding_z_score"],
        )
        decision = client.predict(cf)
        return decision.will_clear

    # Quick sanity check on a few test rows
    print("\nSanity check on 5 test samples:")
    test_df = df[df["split"] == "test"].head(5)
    for _, row in test_df.iterrows():
        features = {}
        for model_feat, df_col in FEATURE_MAP.items():
            val = row.get(df_col, np.nan)
            features[model_feat] = float(val) if not np.isnan(val) else 0.0
        pred = model_predict(features)
        actual_win = row[LABEL_YWIN]
        print(f"  ts={row['ts']} pred={'YES' if pred else 'NO'} actual_win={actual_win} "
              f"y7d_bps={row[LABEL_Y7D]:.1f}")

    # Run walk-forward validation
    print("\n" + "=" * 80)
    print("WALK-FORWARD VALIDATION (6 folds, 70/30, 7-day embargo)")
    print("=" * 80)

    checkpoint_dir = REPO / "reports" / CHECKPOINT_DIR_NAME
    wf_results = run_walk_forward_validation(
        df, model_predict, checkpoint_dir=checkpoint_dir, fresh=args.fresh
    )

    # Run validation report
    # Combine all test returns for the gate
    all_test_returns = np.concatenate([f["returns"] for f in wf_results["fold_results"]])
    # Need in-sample returns too - for simplicity, use train returns from first fold
    # (In practice, this would be a separate train evaluation)
    train_df = df[(df["split"] == "train") & df["usable"]]
    print(f"\nTrain predictions ({len(train_df)} rows, checkpointed every {TRAIN_CHUNK_ROWS}):")
    train_predictions = predict_train_chunked(
        train_df,
        model_predict,
        checkpoint_dir,
        _dataset_fingerprint(df, 6, 0.7),
    )
    train_returns = simulate_carry_returns(train_df, train_predictions)

    report = validation_report(
        returns=train_returns,
        oos_returns=all_test_returns,
        calmar_bar=1.0,
    )

    print("\n" + "=" * 80)
    print("VALIDATION GATE REPORT")
    print("=" * 80)
    print(f"In-sample:")
    print(f"  CAGR: {report['in_sample']['cagr']:.2%}")
    print(f"  Sharpe: {report['in_sample']['sharpe']:.3f}")
    print(f"  MaxDD: {report['in_sample']['max_drawdown']:.2%}")
    print(f"  Calmar: {report['in_sample']['calmar']:.3f}")
    print(f"Out-of-sample:")
    print(f"  CAGR: {report['out_of_sample']['cagr']:.2%}")
    print(f"  Sharpe: {report['out_of_sample']['sharpe']:.3f}")
    print(f"  MaxDD: {report['out_of_sample']['max_drawdown']:.2%}")
    print(f"  Calmar: {report['out_of_sample']['calmar']:.3f}")
    print(f"Has OOS evidence: {report['has_oos_evidence']}")
    print(f"Passes Calmar bar (>=1.0): {report['passes_calmar_bar']}")
    print(f"PBO analysis: {report['pbo_analysis']}")
    print(f"\n>>> CLEARED FOR PAPER TRADING: {report['cleared_for_paper_trading']}")

    # Save results
    import json
    output = {
        "walk_forward": {
            "overall_sharpe": wf_results["sharpe"],
            "overall_calmar": wf_results["calmar"],
            "overall_max_drawdown": wf_results["max_drawdown"],
            "overall_cagr": wf_results["cagr"],
            "overall_num_trades": wf_results["num_trades"],
            "overall_win_rate": wf_results["win_rate"],
            "folds": [
                {
                    "sharpe": f["sharpe"],
                    "calmar": f["calmar"],
                    "max_drawdown": f["max_drawdown"],
                    "cagr": f["cagr"],
                    "num_trades": f["num_trades"],
                    "win_rate": f["win_rate"],
                }
                for f in wf_results["fold_results"]
            ],
        },
        "validation_gate": report,
    }

    out_path = REPO / "reports" / "tars_lora_validation.json"
    out_path.parent.mkdir(exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2, default=str)
    print(f"\nResults saved to {out_path}")

    return 0 if report["cleared_for_paper_trading"] else 1


if __name__ == "__main__":
    sys.exit(main())